ingress: https://www.ekstern.dev.nav.no/syk/feilmeldinger
kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 1
cpu: 100m
memory: 400Mi
db_tier: db-f1-micro
env:
  SPRING_PROFILES_ACTIVE: default