ingress: https://www.nav.no/syk/feilmeldinger
kafkaPool: nav-prod
environment: prod
replicas_min: 2
replicas_max: 3
cpu: 100m
memory: 400Mi
db_tier: db-custom-1-3840
env:
  SPRING_PROFILES_ACTIVE: default
